dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$',
        views.DashboardView.as_view(),
        name='dashboard_page'),

    url(r'^report/$',
        views.ReportView.as_view(),
        name='report_page'),

    url(r'^setting/$',
        views.SettingView.as_view(),
        name='setting_page'),

    url(r'^get_location_data/',
        views.return_location_data,
        name='return_location_data'),

    url(r'^get_report/',
        views.get_report,
        name='get_report'),

]

testAssignment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    # Examples:
    # url(r'^$', 'testAssignment.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^.*$',
        RedirectView.as_view(url=reverse_lazy('users:login'), permanent=False),
        name='index')
]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^login/',
        views.LoginView.as_view(),
        name='login'),

    url(r'^password-change/',
        views.change_password,
        name='password_change'),

    url(r'^logout/$',
        views.LogoutView.as_view(),
        name='logout'),

    url(r'^sign-up/$',
        views.SignUpView.as_view(),
        name='sign_up'),

]

dashboard/models.py
# from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import HttpResponse
from django.views import generic
from users.models import ObjectUser, Location, MapSetting
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from users.core.utils import convert_to_date
import json
# Create your views here.


def return_location_data(request):
    # Return the location Points and details
    # handle ajax request
    return HttpResponse(json.dumps(ObjectUser.get_all_visible_objects(request.user.id)))


def get_report(request):
    # Generate the reports.
    # handle the ajax request.
    start_date = convert_to_date(request.GET.get('start_date', None))
    end_date = convert_to_date(request.GET.get('end_date', None))
    object_id = request.GET.get('object_id', None)
    with_limit = request.GET.get('point_limit', None)
    return HttpResponse(json.dumps(Location.get_report(object_id, start_date, end_date, with_limit)))


class DashboardView(generic.TemplateView):
    """
    View handle and show the dash-board
    """
    template_name = "dashboard/dashboard.html"

    @method_decorator(login_required(login_url=reverse_lazy('users:login')))
    def dispatch(self, request, *args, **kwargs):
        MapSetting.set_settings()  # set the settings
        return super(DashboardView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['points'] = json.dumps(ObjectUser.get_all_visible_objects(self.request.user.id))
        context['start_date'] = self.request.GET.get('start', None)
        context['end_date'] = self.request.GET.get('end', None)
        context['vehicle'] = self.request.GET.get('obj', None)
        objects_list = ObjectUser.get_users_object(self.request.user.id)

        context['objects_list'] = {obj.object.nid: obj.object.name for obj in objects_list}
        return context


class ReportView(generic.TemplateView):
    """
    View handle and show the report-section
    """
    template_name = "dashboard/report-section.html"

    @method_decorator(login_required(login_url=reverse_lazy('users:login')))
    def dispatch(self, request, *args, **kwargs):
        MapSetting.set_settings()  # set the settings
        return super(ReportView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ReportView, self).get_context_data(**kwargs)
        objects_list = ObjectUser.get_users_object(self.request.user.id)
        context['objects_list'] = {obj.object.nid: obj.object.name for obj in objects_list}
        return context


class SettingView(generic.TemplateView):
    """
    View handle and show the report-section
    """
    template_name = "dashboard/setting-section.html"

    @method_decorator(login_required(login_url=reverse_lazy('users:login')))
    def dispatch(self, request, *args, **kwargs):
        MapSetting.set_settings()  # set the settings
        return super(SettingView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SettingView, self).get_context_data(**kwargs)
        objects_list = ObjectUser.get_users_object(self.request.user.id)
        context['objects_list'] = {obj.object.nid: obj.object.name for obj in objects_list}
        return context

dashboard/templates/dashboard/dashboard.html
{% extends "users/layout/base.html" %}
{% load staticfiles %}

{% block css_header %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/openlayer3.css' %}" type="text/css">
{% endblock %}


{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% block body_block %}

    <div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                <p class="bg-success ele-font-size text-center text-success element-pedding {% if message.tags %} {{ message.tags }} {% endif %}">
                    {{ message }}
                </p>
            {% endfor %}
        {% endif %}

        <!-- Main jumbotron for a primary marketing message or call to action -->

        <div class="container-fluid">

            <div class="row-fluid">
                <div class="span12">
                    <div id="map" class="map" tabindex="0"></div>
                    <div class="btn-group" role="group" style='position: absolute; top:30px; right: 40px;'>
                        <a class="btn btn-default" href="{% url 'dashboard:setting_page' %}">Settings</a>
                        <a class="btn btn-default" href="{% url 'users:logout' %}">Logout</a>
                    </div>
                </div>
            </div>

        </div>
        <input hidden="hidden" id="start_date" value="{% if start_date %}{{ start_date }} {% endif %}">
        <input hidden="hidden" id="end_date" value="{% if end_date %}{{ end_date }} {% endif %}">
        <input hidden="hidden" id="vehicle" value="{% if vehicle %}{{ vehicle }} {% endif %}">



        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
    </div>


{% endblock %}

{% block js_footer %}
    {{ block.super }}
    <script src="{% static 'js/bootstarp3.3.5.js' %}"></script>
    <script src="{% static 'js/open-layer3.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/common-script.js' %}"></script>
    <script src="{% static 'js/dashboard-script.js' %}"></script>

{% endblock %}

dashboard/templates/dashboard/report-section.html
{% extends "users/layout/base.html" %}
{% load staticfiles %}

{% block css_header %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/openlayer3.css' %}" type="text/css">
{% endblock %}


{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% block body_block %}

    <div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                <p class="bg-success ele-font-size text-center text-success element-pedding {% if message.tags %} {{ message.tags }} {% endif %}">
                    {{ message }}
                </p>
            {% endfor %}
        {% endif %}
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <span class="navbar-brand">Hello {{ user.username }}</span>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'dashboard:dashboard_page' %}">Map</a></li>
                        <li><a href="{% url 'dashboard:setting_page' %}">Settings</a></li>
                        <li><a href="{% url 'users:password_change' %}">Change Password</a></li>
                        <li><a href="{% url 'users:logout' %}">Log-out</a></li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>



    <div class="container">
            {% if objects_list %}
                <div class="panel panel-default">
                    <div class="panel-heading">Report Generation</div>
                    <div class="panel-body">

                    <div class='col-md-2'>
                        <label for="object_id" class="control-label">Vehicle</label>
                        <select id="object_id" class="form-control">
                            {% for key, value in objects_list.items %}

                                <option value="{{ key }}">{{ value }}</option>
                            {% endfor %}
                        </select>
                    </div>

                        <div class='col-md-5'>
                            <div class="form-group">
                                <label for="datetimepicker6">&nbsp;</label>
                                <div class='input-group date' id='datetimepicker6'>
                                    <input type='text' class="form-control" placeholder="Start Date/Time" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                                </div>
                            </div>
                        </div>
                        <div class='col-md-5'>
                            <div class="form-group">
                                <label for="datetimepicker7">&nbsp;</label>
                                <div class='input-group date' id='datetimepicker7'>
                                    <input type='text' class="form-control" placeholder="End Date/Time" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                                </div>
                            </div>
                        </div>
                        <div class='col-md-5'>
                            <div class="form-group">
                                <div class='input-group date'>
                                    <button type="button" class="btn btn-primary" id="report_generate">Generate Report</button>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>



        <div class="container">
            <div class="row" id="reports"></div>
        </div>
        <!-- /.modal -->
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
    </div>


{% endblock %}

{% block js_footer %}
    {{ block.super }}
    <script src="{% static 'js/bootstarp3.3.5.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/common-script.js' %}"></script>
    <script src="{% static 'js/report-script.js' %}"></script>

{% endblock %}

dashboard/templates/dashboard/setting-section.html
{% extends "users/layout/base.html" %}
{% load staticfiles %}

{% block css_header %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/openlayer3.css' %}" type="text/css">
{% endblock %}


{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% block body_block %}

    <div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                <p class="bg-success ele-font-size text-center text-success element-pedding {% if message.tags %} {{ message.tags }} {% endif %}">
                    {{ message }}
                </p>
            {% endfor %}
        {% endif %}
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <span class="navbar-brand">Hello {{ user.username }}</span>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'dashboard:dashboard_page' %}">Map</a></li>
                        <li><a href="{% url 'dashboard:setting_page' %}">Settings</a></li>
                        <li><a href="{% url 'users:password_change' %}">Change Password</a></li>
                        <li><a href="{% url 'users:logout' %}">Log-out</a></li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>

        <div class="container">
            {% if objects_list %}
                <div class="panel panel-default">
                    <div class="panel-heading">Select the Time Range</div>
                    <div class="panel-body">
                        <div class='col-md-2'>
                        <label for="disabledSelect">Vehicle</label>
                            <select id="selected_object_id" class="form-control">
                                {% for key, value in objects_list.items %}
                                    <option value="{{ key }}">{{ value }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class='col-md-5'>
                            <div class="form-group">
                                <label for="initialDateTime">&nbsp;</label>
                                <div class='input-group date' id='initialDateTime'>
                                    <input type='text' class="form-control" placeholder="Start Date/Time"/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class='col-md-5'>
                            <div class="form-group">
                                <label for="endingDateTime">&nbsp;</label>
                                <div class='input-group date' id='endingDateTime'>
                                    <input type='text' class="form-control" placeholder="End Date/Time"/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class='col-md-5'>
                            <div class="form-group">
                                <div class='input-group date'>
                                    <button type="button" class="btn btn-primary" id="object_detail" data-redirect="{% url 'dashboard:dashboard_page' %}">Filter Data on Map</button>
                                    <a href="{% url 'dashboard:report_page' %}">Generate Report</a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>

    </div>


{% endblock %}

{% block js_footer %}
    {{ block.super }}
    <script src="{% static 'js/bootstarp3.3.5.js' %}"></script>
    <script src="{% static 'js/open-layer3.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/setting-script.js' %}"></script>

{% endblock %}